### ISSUE TITLE
App Router choice (stdlib or 3rd party)

### ISSUE THREAD

**Issue by adoublef** [rog-golang-buddies/rmx#8]
Opinions on using the stdlib or a 3rd party for our router.

I know that if the project was all static endpoints and we were just making sure each endpoint could only be accessed by a certain method, that can be easily achieved with the stdlib. If we end up having a few dynamic endpoints maybe a 3rd party is more appropriate as it would take care of that with its utility functions.

[Here](https://benhoyt.com/writings/go-routing/) is a decent blog that shows a few ways we could deal with dynamic endpoints using the stdlib as well as pros&cons for various methods.

**Comment by pmoieni** [comment]
I agree. This is different from an ORM. Instead of focusing on the project we need to write lots of functions to solve the problems that are already solved by the routers.
+1 for `chi`. It's lightweight and it's a fork of Julien Schmidt's httprouter( https://github.com/julienschmidt/httprouter) which  we can use that too.

**Comment by hansvb** [comment]
I'll just leave this here for now: https://awesome-go.com/#routers (27 different routers to choose from ATM 😅)

**Comment by adoublef** [comment]
Though I am comfortable with `chi` and likely upvote that decision too, I will look through that list for competitors. I think I'll first filter all the options that use standard `http.HandlerFunc` handlers, as this gives the greatest flexibility in-case we choose to move to something else later. I feel routers that deviate from the standard definition is a no-go.

**Comment by adoublef** [comment]
> I agree. This is different from an ORM. Instead of focusing on the project we need to write lots of functions to solve the problems that are already solved by the routers. +1 for `chi`. It's lightweight and it's a fork of Julien Schmidt's httprouter( https://github.com/julienschmidt/httprouter) which we can use that too.

Yh I would steer away from httprouter, purely because the handler definition breaks cohesion with the stdlib. Meaning we could get pigeon hold, if we ever try to switch our router decision.
